
export const translations = {
    "noRowsLabel": "אין שורות",
    "noResultsOverlayLabel": "לא נמצאו תוצאות.",
    "noColumnsOverlayLabel": "אין עמודות",
    "noColumnsOverlayManageColumns": "ניהול עמודות",
    "emptyPivotOverlayLabel": "הוסף שדות לשורות, עמודות וערכים כדי ליצור טבלת ציר",

    "toolbarDensity": "צפיפות",
    "toolbarDensityLabel": "צפיפות",
    "toolbarDensityCompact": "קומפקטי",
    "toolbarDensityStandard": "סטנדרטי",
    "toolbarDensityComfortable": "נוח",

    "toolbarColumns": "עמודות",
    "toolbarColumnsLabel": "בחר עמודות",

    "toolbarFilters": "סינונים",
    "toolbarFiltersLabel": "הצג סינונים",
    "toolbarFiltersTooltipHide": "הסתר סינונים",
    "toolbarFiltersTooltipShow": "הצג סינונים",

    "toolbarQuickFilterPlaceholder": "חיפוש…",
    "toolbarQuickFilterLabel": "חיפוש",
    "toolbarQuickFilterDeleteIconLabel": "נקה",

    "toolbarExport": "ייצוא",
    "toolbarExportLabel": "ייצוא",
    "toolbarExportCSV": "הורד כ-CSV",
    "toolbarExportPrint": "הדפס",
    "toolbarExportExcel": "הורד כ-Excel",

    "toolbarPivot": "ציר",
    "toolbarAssistant": "עוזר בינה מלאכותית",

    "columnsManagementSearchTitle": "חיפוש",
    "columnsManagementNoColumns": "אין עמודות",
    "columnsManagementShowHideAllText": "הצג/הסתר הכל",
    "columnsManagementReset": "איפוס",
    "columnsManagementDeleteIconLabel": "נקה",

    "filterPanelAddFilter": "הוסף מסנן",
    "filterPanelRemoveAll": "הסר הכל",
    "filterPanelDeleteIconLabel": "מחק",
    "filterPanelLogicOperator": "אופרטור לוגי",
    "filterPanelOperator": "אופרטור",
    "filterPanelOperatorAnd": "וגם",
    "filterPanelOperatorOr": "או",
    "filterPanelColumns": "עמודות",
    "filterPanelInputLabel": "ערך",
    "filterPanelInputPlaceholder": "ערך לסינון",

    "filterOperatorContains": "מכיל",
    "filterOperatorDoesNotContain": "לא מכיל",
    "filterOperatorEquals": "שווה ל",
    "filterOperatorDoesNotEqual": "שונה מ",
    "filterOperatorStartsWith": "מתחיל ב",
    "filterOperatorEndsWith": "מסתיים ב",
    "filterOperatorIs": "הוא",
    "filterOperatorNot": "אינו",
    "filterOperatorAfter": "אחרי",
    "filterOperatorOnOrAfter": "ביום או אחרי",
    "filterOperatorBefore": "לפני",
    "filterOperatorOnOrBefore": "ביום או לפני",
    "filterOperatorIsEmpty": "ריק",
    "filterOperatorIsNotEmpty": "אינו ריק",
    "filterOperatorIsAnyOf": "הוא אחד מ",
    "filterOperator=": "=",
    "filterOperator!=": "!=",
    "filterOperator>": ">",
    "filterOperator>=": ">=",
    "filterOperator<": "<",
    "filterOperator<=": "<=",

    "headerFilterOperatorContains": "מכיל",
    "headerFilterOperatorDoesNotContain": "לא מכיל",
    "headerFilterOperatorEquals": "שווה ל",
    "headerFilterOperatorDoesNotEqual": "שונה מ",
    "headerFilterOperatorStartsWith": "מתחיל ב",
    "headerFilterOperatorEndsWith": "מסתיים ב",
    "headerFilterOperatorIs": "הוא",
    "headerFilterOperatorNot": "אינו",
    "headerFilterOperatorAfter": "אחרי",
    "headerFilterOperatorOnOrAfter": "ביום או אחרי",
    "headerFilterOperatorBefore": "לפני",
    "headerFilterOperatorOnOrBefore": "ביום או לפני",
    "headerFilterOperatorIsEmpty": "ריק",
    "headerFilterOperatorIsNotEmpty": "אינו ריק",
    "headerFilterOperatorIsAnyOf": "הוא אחד מ",
    "headerFilterOperator=": "שווה ל",
    "headerFilterOperator!=": "לא שווה ל",
    "headerFilterOperator>": "גדול מ",
    "headerFilterOperator>=": "גדול או שווה ל",
    "headerFilterOperator<": "קטן מ",
    "headerFilterOperator<=": "קטן או שווה ל",
    "headerFilterClear": "נקה מסנן",

    "filterValueAny": "כלשהו",
    "filterValueTrue": "אמת",
    "filterValueFalse": "שקר",

    "columnMenuLabel": "תפריט",
    "columnMenuShowColumns": "הצג עמודות",
    "columnMenuManageColumns": "נהל עמודות",
    "columnMenuFilter": "סינון",
    "columnMenuHideColumn": "הסתר עמודה",
    "columnMenuUnsort": "בטל מיון",
    "columnMenuSortAsc": "מיין עולה",
    "columnMenuSortDesc": "מיין יורד",
    "columnMenuManagePivot": "נהל ציר",

    "columnHeaderFiltersLabel": "הצג סינונים",
    "columnHeaderSortIconLabel": "מיון",

    "footerTotalRows": "סה\"כ שורות:",

    "checkboxSelectionHeaderName": "בחירת תיבה",
    "checkboxSelectionSelectAllRows": "בחר את כל השורות",
    "checkboxSelectionUnselectAllRows": "בטל בחירת כל השורות",
    "checkboxSelectionSelectRow": "בחר שורה",
    "checkboxSelectionUnselectRow": "בטל בחירת שורה",

    "booleanCellTrueLabel": "כן",
    "booleanCellFalseLabel": "לא",

    "actionsCellMore": "עוד",

    "pinToLeft": "הצמד לשמאל",
    "pinToRight": "הצמד לימין",
    "unpin": "בטל הצמדה",

    "treeDataGroupingHeaderName": "קיבוץ",
    "treeDataExpand": "הצג ילדים",
    "treeDataCollapse": "הסתר ילדים",

    "groupingColumnHeaderName": "קיבוץ",

    "detailPanelToggle": "הצגת פרטי שורה",
    "expandDetailPanel": "הרחב",
    "collapseDetailPanel": "כווץ",

    "paginationRowsPerPage": "שורות לעמוד:",

    "rowReorderingHeaderName": "סידור שורות",

    "aggregationMenuItemHeader": "אגרגציה",
    "aggregationFunctionLabelSum": "סכום",
    "aggregationFunctionLabelAvg": "ממוצע",
    "aggregationFunctionLabelMin": "מינימום",
    "aggregationFunctionLabelMax": "מקסימום",
    "aggregationFunctionLabelSize": "גודל",

    "pivotToggleLabel": "ציר",
    "pivotRows": "שורות",
    "pivotColumns": "עמודות",
    "pivotValues": "ערכים",
    "pivotCloseButton": "סגור הגדרות ציר",
    "pivotSearchButton": "חפש שדות",
    "pivotSearchControlPlaceholder": "חפש שדות",
    "pivotSearchControlLabel": "חפש שדות",
    "pivotSearchControlClear": "נקה חיפוש",
    "pivotNoFields": "אין שדות",
    "pivotMenuMoveUp": "העבר למעלה",
    "pivotMenuMoveDown": "העבר למטה",
    "pivotMenuMoveToTop": "העבר לראש",
    "pivotMenuMoveToBottom": "העבר לסוף",
    "pivotMenuRows": "שורות",
    "pivotMenuColumns": "עמודות",
    "pivotMenuValues": "ערכים",
    "pivotMenuOptions": "אפשרויות שדה",
    "pivotMenuAddToRows": "הוסף לשורות",
    "pivotMenuAddToColumns": "הוסף לעמודות",
    "pivotMenuAddToValues": "הוסף לערכים",
    "pivotMenuRemove": "הסר",
    "pivotDragToRows": "גרור לכאן כדי ליצור שורות",
    "pivotDragToColumns": "גרור לכאן כדי ליצור עמודות",
    "pivotDragToValues": "גרור לכאן כדי ליצור ערכים",
    "pivotYearColumnHeaderName": "(שנה)",
    "pivotQuarterColumnHeaderName": "(רבעון)",

    "aiAssistantPanelTitle": "עוזר בינה מלאכותית",
    "aiAssistantPanelClose": "סגור עוזר",
    "aiAssistantPanelNewConversation": "שיחה חדשה",
    "aiAssistantPanelConversationHistory": "היסטוריית שיחות",
    "aiAssistantPanelEmptyConversation": "אין היסטוריית פקודות",
    "aiAssistantSuggestions": "הצעות",

    "promptFieldLabel": "פקודה",
    "promptFieldPlaceholder": "הקלד פקודה…",
    "promptFieldPlaceholderWithRecording": "הקלד או הקלט פקודה…",
    "promptFieldPlaceholderListening": "מאזין לפקודה…",
    "promptFieldSpeechRecognitionNotSupported": "זיהוי דיבור לא נתמך בדפדפן זה",
    "promptFieldSend": "שלח",
    "promptFieldRecord": "הקלט",
    "promptFieldStopRecording": "הפסק הקלטה",

    "promptRerun": "הפעל מחדש",
    "promptProcessing": "מעבד…",
    "promptAppliedChanges": "שינויים הוחלו"
}
